<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Typst.Renderer.Native.win-x64</PackageId>
    <Description>Windows x64 native runtime for Typst.Renderer</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecFile>Typst.Renderer.Native.win-x64.nuspec</NuspecFile>
    <NuspecProperties>version=$(Version)</NuspecProperties>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Typst.Renderer\Typst.Renderer.csproj" PrivateAssets="all" />
    <None Include="_._" Pack="true" PackagePath="lib/net8.0/" />
    <None Include="..\..\artifacts\native\win-x64\typst_dotnet_native.dll" Pack="true" PackagePath="runtimes/win-x64/native/" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
