<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <CetzNativePackage Condition="'$(CetzNativePackage)' == ''">Cetz.Renderer.Native.win-x64</CetzNativePackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="$(CetzNativePackage)" Version="0.1.0" />
  </ItemGroup>
</Project>
