<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TypstNativePackage Condition="'$(TypstNativePackage)' == ''">Typst.Renderer.Native.win-x64</TypstNativePackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="$(TypstNativePackage)" Version="[$(TypstPackageVersion)]" />
  </ItemGroup>
</Project>
