<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <ProjectReference Include="..\..\src\Typst.Renderer\Typst.Renderer.csproj" />
    <ProjectReference Include="..\..\src\Typst.Renderer.Core\Typst.Renderer.Core.csproj" />
    <ProjectReference Include="..\..\src\Typst.Renderer.Uno\Typst.Renderer.Uno.csproj" />
    <ProjectReference Include="..\..\samples\Typst.Renderer.Demo.Shared\Typst.Renderer.Demo.Shared.csproj" />
  </ItemGroup>
</Project>
