<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Cetz.Renderer.Avalonia</PackageId>
    <Description>Avalonia controls for Cetz.Renderer.Core documents</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cetz.Renderer.Core\Cetz.Renderer.Core.csproj" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
