<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Typst.Renderer.Demo.Shared</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Typst.Renderer\Typst.Renderer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>
</Project>
